version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - mkdir package
      - if [ -s lambda/requirements.txt ]; then pip install -r lambda/requirements.txt -t package; fi

  build:
    commands:
      - cp lambda/*.py package/

artifacts:
  base-directory: package
  files:
    - '**/*'