version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python -m pip install --upgrade pip
      - mkdir -p package
      - pip install -r lambda/requirements.txt -t package

  build:
    commands:
      - cp lambda/*.py package/
      - cd package && zip -r ../lambda-package.zip .
      - cd ..
      - aws lambda update-function-code --function-name covid-lambda --zip-file fileb://lambda-package.zip
      - echo "covid Lambda functions updated successfully."
      - aws lambda update-function-code --function-name vaccine-lambda --zip-file fileb://lambda-package.zip
      - echo "vaccine Lambda functions updated successfully."
      - aws lambda update-function-code --function-name hospital-lambda --zip-file fileb://lambda-package.zip
      - echo "hospital Lambda functions updated successfully."

artifacts:
  files:
    - lambda-package.zip
